[misc] skip east run in case of a missing dev env
Signed-off-by: Jakob Ackermann <das7pad@outlook.com>

diff --git a/bin/east b/bin/east
--- a/bin/east
+++ b/bin/east
@@ -5,6 +5,9 @@ SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 if [ -f /.dockerenv ]; then
   # I'm running inside docker
   npm run migrations -- "$@"
+elif [ ! -e "$SCRIPTPATH/../../bin/run" ]; then
+  # ...or hello OSS Developer!
+  echo "dev env is missing - skipping migrations" >&2
 else
   ${SCRIPTPATH}/run web_v2 bin/east "$@"
 fi
